services:
  - type: web
    name: church-attendance
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
